// Generated by rstantools.  Do not edit by hand.

/*
    eDNA_structure is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    eDNA_structure is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with eDNA_structure.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_dmm_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 98> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 69, column 2 to column 25)",
  " (in 'string', line 72, column 2 to column 28)",
  " (in 'string', line 74, column 2 to column 22)",
  " (in 'string', line 78, column 2 to column 34)",
  " (in 'string', line 110, column 2 to column 31)",
  " (in 'string', line 112, column 2 to column 39)",
  " (in 'string', line 114, column 2 to column 20)",
  " (in 'string', line 84, column 6 to column 49)",
  " (in 'string', line 83, column 11 to line 85, column 5)",
  " (in 'string', line 81, column 13 to column 14)",
  " (in 'string', line 81, column 16 to column 21)",
  " (in 'string', line 81, column 6 to column 46)",
  " (in 'string', line 82, column 6 to column 63)",
  " (in 'string', line 80, column 15 to line 83, column 5)",
  " (in 'string', line 80, column 4 to line 85, column 5)",
  " (in 'string', line 79, column 2 to line 86, column 3)",
  " (in 'string', line 116, column 11 to column 12)",
  " (in 'string', line 116, column 4 to column 64)",
  " (in 'string', line 117, column 11 to column 12)",
  " (in 'string', line 117, column 4 to column 17)",
  " (in 'string', line 119, column 13 to column 14)",
  " (in 'string', line 119, column 6 to column 40)",
  " (in 'string', line 120, column 6 to column 66)",
  " (in 'string', line 122, column 8 to column 64)",
  " (in 'string', line 121, column 6 to line 122, column 64)",
  " (in 'string', line 123, column 6 to column 34)",
  " (in 'string', line 118, column 19 to line 124, column 5)",
  " (in 'string', line 118, column 4 to line 124, column 5)",
  " (in 'string', line 125, column 4 to column 41)",
  " (in 'string', line 126, column 11 to column 12)",
  " (in 'string', line 126, column 4 to column 37)",
  " (in 'string', line 127, column 4 to column 31)",
  " (in 'string', line 128, column 4 to column 47)",
  " (in 'string', line 115, column 17 to line 129, column 3)",
  " (in 'string', line 115, column 2 to line 129, column 3)",
  " (in 'string', line 91, column 4 to column 43)",
  " (in 'string', line 90, column 2 to line 91, column 43)",
  " (in 'string', line 92, column 2 to column 35)",
  " (in 'string', line 93, column 2 to column 41)",
  " (in 'string', line 96, column 11 to column 12)",
  " (in 'string', line 96, column 4 to column 64)",
  " (in 'string', line 97, column 11 to column 12)",
  " (in 'string', line 97, column 4 to column 17)",
  " (in 'string', line 99, column 13 to column 14)",
  " (in 'string', line 99, column 6 to column 40)",
  " (in 'string', line 100, column 6 to column 66)",
  " (in 'string', line 102, column 8 to column 64)",
  " (in 'string', line 101, column 6 to line 102, column 64)",
  " (in 'string', line 103, column 6 to column 34)",
  " (in 'string', line 98, column 19 to line 104, column 5)",
  " (in 'string', line 98, column 4 to line 104, column 5)",
  " (in 'string', line 105, column 4 to column 30)",
  " (in 'string', line 95, column 17 to line 106, column 3)",
  " (in 'string', line 95, column 2 to line 106, column 3)",
  " (in 'string', line 33, column 2 to column 17)",
  " (in 'string', line 34, column 2 to column 17)",
  " (in 'string', line 35, column 2 to column 17)",
  " (in 'string', line 36, column 2 to column 17)",
  " (in 'string', line 37, column 8 to column 9)",
  " (in 'string', line 37, column 11 to column 12)",
  " (in 'string', line 37, column 2 to column 29)",
  " (in 'string', line 38, column 9 to column 10)",
  " (in 'string', line 38, column 12 to column 13)",
  " (in 'string', line 38, column 2 to column 26)",
  " (in 'string', line 39, column 2 to column 21)",
  " (in 'string', line 43, column 2 to column 28)",
  " (in 'string', line 44, column 2 to column 27)",
  " (in 'string', line 49, column 8 to column 9)",
  " (in 'string', line 49, column 2 to column 27)",
  " (in 'string', line 50, column 17 to column 35)",
  " (in 'string', line 50, column 2 to column 35)",
  " (in 'string', line 52, column 9 to column 10)",
  " (in 'string', line 52, column 2 to column 19)",
  " (in 'string', line 54, column 4 to column 35)",
  " (in 'string', line 55, column 19 to column 48)",
  " (in 'string', line 55, column 4 to column 48)",
  " (in 'string', line 56, column 4 to column 20)",
  " (in 'string', line 53, column 17 to line 57, column 3)",
  " (in 'string', line 53, column 2 to line 57, column 3)",
  " (in 'string', line 60, column 9 to column 10)",
  " (in 'string', line 60, column 12 to column 17)",
  " (in 'string', line 60, column 2 to column 28)",
  " (in 'string', line 64, column 4 to column 37)",
  " (in 'string', line 63, column 9 to line 65, column 3)",
  " (in 'string', line 62, column 4 to column 58)",
  " (in 'string', line 61, column 13 to line 63, column 3)",
  " (in 'string', line 61, column 2 to line 65, column 3)",
  " (in 'string', line 69, column 8 to column 9)",
  " (in 'string', line 69, column 19 to column 20)",
  " (in 'string', line 72, column 9 to column 14)",
  " (in 'string', line 72, column 16 to column 21)",
  " (in 'string', line 78, column 9 to column 10)",
  " (in 'string', line 78, column 12 to column 13)",
  " (in 'string', line 110, column 9 to column 10)",
  " (in 'string', line 110, column 12 to column 13)",
  " (in 'string', line 112, column 8 to column 9)",
  " (in 'string', line 114, column 9 to column 10)"};
#include <stan_meta_header.hpp>
class model_dmm final : public model_base_crtp<model_dmm> {
private:
  int N;
  int S;
  int K;
  int P;
  std::vector<std::vector<int>> X;
  Eigen::Matrix<double,-1,-1> covariates_data__;
  double conc;
  double alpha_shape;
  double alpha_rate;
  std::vector<int> Ni;
  Eigen::Matrix<double,-1,1> log_mc_data__;
  Eigen::Matrix<double,-1,-1> X_design_data__;
  int beta_1dim__;
  int beta_2dim__;
  Eigen::Map<Eigen::Matrix<double,-1,-1>> covariates{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> log_mc{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X_design{nullptr, 0, 0};
public:
  ~model_dmm() {}
  model_dmm(stan::io::var_context& context__, unsigned int random_seed__ = 0,
            std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_dmm_namespace::model_dmm";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 55;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 55;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 55;
      stan::math::check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 56;
      context__.validate_dims("data initialization", "S", "int",
        std::vector<size_t>{});
      S = std::numeric_limits<int>::min();
      current_statement__ = 56;
      S = context__.vals_i("S")[(1 - 1)];
      current_statement__ = 56;
      stan::math::check_greater_or_equal(function__, "S", S, 1);
      current_statement__ = 57;
      context__.validate_dims("data initialization", "K", "int",
        std::vector<size_t>{});
      K = std::numeric_limits<int>::min();
      current_statement__ = 57;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 57;
      stan::math::check_greater_or_equal(function__, "K", K, 2);
      current_statement__ = 58;
      context__.validate_dims("data initialization", "P", "int",
        std::vector<size_t>{});
      P = std::numeric_limits<int>::min();
      current_statement__ = 58;
      P = context__.vals_i("P")[(1 - 1)];
      current_statement__ = 58;
      stan::math::check_greater_or_equal(function__, "P", P, 0);
      current_statement__ = 59;
      stan::math::validate_non_negative_index("X", "N", N);
      current_statement__ = 60;
      stan::math::validate_non_negative_index("X", "S", S);
      current_statement__ = 61;
      context__.validate_dims("data initialization", "X", "int",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(S)});
      X = std::vector<std::vector<int>>(N,
            std::vector<int>(S, std::numeric_limits<int>::min()));
      {
        std::vector<int> X_flat__;
        current_statement__ = 61;
        X_flat__ = context__.vals_i("X");
        current_statement__ = 61;
        pos__ = 1;
        current_statement__ = 61;
        for (int sym1__ = 1; sym1__ <= S; ++sym1__) {
          current_statement__ = 61;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 61;
            stan::model::assign(X, X_flat__[(pos__ - 1)],
              "assigning variable X", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 61;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 61;
      stan::math::check_greater_or_equal(function__, "X", X, 0);
      current_statement__ = 62;
      stan::math::validate_non_negative_index("covariates", "N", N);
      current_statement__ = 63;
      stan::math::validate_non_negative_index("covariates", "P", P);
      current_statement__ = 64;
      context__.validate_dims("data initialization", "covariates", "double",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(P)});
      covariates_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, P,
                            std::numeric_limits<double>::quiet_NaN());
      new (&covariates)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(covariates_data__.data(), N,
        P);
      {
        std::vector<local_scalar_t__> covariates_flat__;
        current_statement__ = 64;
        covariates_flat__ = context__.vals_r("covariates");
        current_statement__ = 64;
        pos__ = 1;
        current_statement__ = 64;
        for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
          current_statement__ = 64;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 64;
            stan::model::assign(covariates, covariates_flat__[(pos__ - 1)],
              "assigning variable covariates",
              stan::model::index_uni(sym2__), stan::model::index_uni(sym1__));
            current_statement__ = 64;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 65;
      context__.validate_dims("data initialization", "conc", "double",
        std::vector<size_t>{});
      conc = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 65;
      conc = context__.vals_r("conc")[(1 - 1)];
      current_statement__ = 65;
      stan::math::check_greater_or_equal(function__, "conc", conc, 0);
      current_statement__ = 66;
      context__.validate_dims("data initialization", "alpha_shape", "double",
        std::vector<size_t>{});
      alpha_shape = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 66;
      alpha_shape = context__.vals_r("alpha_shape")[(1 - 1)];
      current_statement__ = 66;
      stan::math::check_greater_or_equal(function__, "alpha_shape",
        alpha_shape, 0);
      current_statement__ = 67;
      context__.validate_dims("data initialization", "alpha_rate", "double",
        std::vector<size_t>{});
      alpha_rate = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 67;
      alpha_rate = context__.vals_r("alpha_rate")[(1 - 1)];
      current_statement__ = 67;
      stan::math::check_greater_or_equal(function__, "alpha_rate",
        alpha_rate, 0);
      current_statement__ = 68;
      stan::math::validate_non_negative_index("Ni", "N", N);
      current_statement__ = 69;
      Ni = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 71;
      for (int i = 1; i <= N; ++i) {
        current_statement__ = 70;
        stan::model::assign(Ni,
          stan::math::sum(
            stan::model::rvalue(X, "X", stan::model::index_uni(i))),
          "assigning variable Ni", stan::model::index_uni(i));
      }
      current_statement__ = 72;
      stan::math::validate_non_negative_index("log_mc", "N", N);
      current_statement__ = 73;
      log_mc_data__ = Eigen::Matrix<double,-1,1>::Constant(N,
                        std::numeric_limits<double>::quiet_NaN());
      new (&log_mc)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(log_mc_data__.data(), N);
      current_statement__ = 79;
      for (int i = 1; i <= N; ++i) {
        double lmc = std::numeric_limits<double>::quiet_NaN();
        current_statement__ = 74;
        lmc = stan::math::lgamma(
                (stan::model::rvalue(Ni, "Ni", stan::model::index_uni(i)) +
                1.0));
        current_statement__ = 76;
        for (int s = 1; s <= S; ++s) {
          current_statement__ = 75;
          lmc = (lmc -
            stan::math::lgamma(
              (stan::model::rvalue(X, "X", stan::model::index_uni(i),
                 stan::model::index_uni(s)) + 1.0)));
        }
        current_statement__ = 77;
        stan::model::assign(log_mc, lmc, "assigning variable log_mc",
          stan::model::index_uni(i));
      }
      current_statement__ = 80;
      stan::math::validate_non_negative_index("X_design", "N", N);
      current_statement__ = 81;
      stan::math::validate_non_negative_index("X_design", "P + 1", (P + 1));
      current_statement__ = 82;
      X_design_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, (P + 1),
                          std::numeric_limits<double>::quiet_NaN());
      new (&X_design)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_design_data__.data(), N, (P
        + 1));
      current_statement__ = 87;
      if (stan::math::logical_gt(P, 0)) {
        current_statement__ = 85;
        stan::model::assign(X_design,
          stan::math::append_col(stan::math::rep_vector(1.0, N), covariates),
          "assigning variable X_design");
      } else {
        current_statement__ = 83;
        stan::model::assign(X_design, stan::math::rep_matrix(1.0, N, 1),
          "assigning variable X_design");
      }
      current_statement__ = 69;
      stan::math::check_greater_or_equal(function__, "Ni", Ni, 0);
      current_statement__ = 88;
      stan::math::validate_non_negative_index("pi", "K", K);
      current_statement__ = 89;
      stan::math::validate_positive_index("pi", "S", S);
      current_statement__ = 90;
      beta_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 90;
      beta_1dim__ = (K - 1);
      current_statement__ = 90;
      stan::math::validate_non_negative_index("beta", "K - 1", beta_1dim__);
      current_statement__ = 91;
      beta_2dim__ = std::numeric_limits<int>::min();
      current_statement__ = 91;
      beta_2dim__ = (P + 1);
      current_statement__ = 91;
      stan::math::validate_non_negative_index("beta", "P + 1", beta_2dim__);
      current_statement__ = 92;
      stan::math::validate_non_negative_index("log_mixing_weights", "N", N);
      current_statement__ = 93;
      stan::math::validate_non_negative_index("log_mixing_weights", "K", K);
      current_statement__ = 94;
      stan::math::validate_non_negative_index("community_probs", "N", N);
      current_statement__ = 95;
      stan::math::validate_non_negative_index("community_probs", "K", K);
      current_statement__ = 96;
      stan::math::validate_non_negative_index("z_hat", "N", N);
      current_statement__ = 97;
      stan::math::validate_non_negative_index("log_lik", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = (K * (S - 1)) + (beta_1dim__ * beta_2dim__) + 1;
  }
  inline std::string model_name() const final {
    return "model_dmm";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ = "model_dmm_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> pi =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(K,
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__));
      current_statement__ = 1;
      pi = in__.template read_constrain_simplex<
             std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>,
             jacobian__>(lp__, K, S);
      Eigen::Matrix<local_scalar_t__,-1,-1> beta =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(beta_1dim__,
          beta_2dim__, DUMMY_VAR__);
      current_statement__ = 2;
      beta = in__.template read<
               Eigen::Matrix<local_scalar_t__,-1,-1>>(beta_1dim__,
               beta_2dim__);
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 3;
      alpha = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      Eigen::Matrix<local_scalar_t__,-1,-1> log_mixing_weights =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N, K, DUMMY_VAR__);
      {
        current_statement__ = 15;
        if (stan::math::logical_gt(K, 1)) {
          current_statement__ = 10;
          stan::math::validate_non_negative_index("eta", "N", N);
          current_statement__ = 11;
          stan::math::validate_non_negative_index("eta", "K - 1", (K - 1));
          Eigen::Matrix<local_scalar_t__,-1,-1> eta =
            Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N, (K - 1),
              DUMMY_VAR__);
          current_statement__ = 12;
          stan::model::assign(eta,
            stan::math::multiply(X_design, stan::math::transpose(beta)),
            "assigning variable eta");
          current_statement__ = 13;
          stan::model::assign(log_mixing_weights,
            stan::math::append_col(eta, stan::math::rep_vector(0.0, N)),
            "assigning variable log_mixing_weights");
        } else {
          current_statement__ = 8;
          stan::model::assign(log_mixing_weights,
            stan::math::rep_matrix(0.0, N, 1),
            "assigning variable log_mixing_weights");
        }
      }
      {
        current_statement__ = 37;
        for (int k = 1; k <= K; ++k) {
          current_statement__ = 36;
          lp_accum__.add(stan::math::dirichlet_lpdf<propto__>(
                           stan::model::rvalue(pi, "pi",
                             stan::model::index_uni(k)),
                           stan::math::rep_vector(conc, S)));
        }
        current_statement__ = 38;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(
                         stan::math::to_vector(beta), 0, 1.0));
        current_statement__ = 39;
        lp_accum__.add(stan::math::gamma_lpdf<propto__>(alpha, alpha_shape,
                         alpha_rate));
        current_statement__ = 54;
        for (int i = 1; i <= N; ++i) {
          current_statement__ = 40;
          stan::math::validate_non_negative_index("log_weights", "K", K);
          Eigen::Matrix<local_scalar_t__,-1,1> log_weights =
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
          current_statement__ = 41;
          stan::model::assign(log_weights,
            stan::math::log_softmax(
              stan::math::transpose(
                stan::model::rvalue(log_mixing_weights, "log_mixing_weights",
                  stan::model::index_uni(i)))),
            "assigning variable log_weights");
          current_statement__ = 42;
          stan::math::validate_non_negative_index("lp", "K", K);
          Eigen::Matrix<local_scalar_t__,-1,1> lp =
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
          current_statement__ = 51;
          for (int k = 1; k <= K; ++k) {
            current_statement__ = 44;
            stan::math::validate_non_negative_index("alpha_k", "S", S);
            Eigen::Matrix<local_scalar_t__,-1,1> alpha_k =
              Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
            current_statement__ = 45;
            stan::model::assign(alpha_k,
              stan::math::multiply(alpha,
                stan::model::rvalue(pi, "pi", stan::model::index_uni(k))),
              "assigning variable alpha_k");
            local_scalar_t__ dm = DUMMY_VAR__;
            current_statement__ = 46;
            dm = ((stan::model::rvalue(log_mc, "log_mc",
                     stan::model::index_uni(i))
              + stan::math::lgamma(alpha)) -
              stan::math::lgamma(
                (stan::model::rvalue(Ni, "Ni", stan::model::index_uni(i)) +
                alpha)));
            current_statement__ = 48;
            for (int s = 1; s <= S; ++s) {
              current_statement__ = 47;
              dm = (dm +
                (stan::math::lgamma(
                   (stan::model::rvalue(X, "X", stan::model::index_uni(i),
                      stan::model::index_uni(s)) +
                   stan::model::rvalue(alpha_k, "alpha_k",
                     stan::model::index_uni(s))))
                -
                stan::math::lgamma(
                  stan::model::rvalue(alpha_k, "alpha_k",
                    stan::model::index_uni(s)))));
            }
            current_statement__ = 49;
            stan::model::assign(lp,
              (stan::model::rvalue(log_weights, "log_weights",
                 stan::model::index_uni(k)) + dm), "assigning variable lp",
              stan::model::index_uni(k));
          }
          current_statement__ = 52;
          lp_accum__.add(stan::math::log_sum_exp(lp));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_dmm_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      std::vector<Eigen::Matrix<double,-1,1>> pi =
        std::vector<Eigen::Matrix<double,-1,1>>(K,
          Eigen::Matrix<double,-1,1>::Constant(S,
            std::numeric_limits<double>::quiet_NaN()));
      current_statement__ = 1;
      pi = in__.template read_constrain_simplex<
             std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>,
             jacobian__>(lp__, K, S);
      Eigen::Matrix<double,-1,-1> beta =
        Eigen::Matrix<double,-1,-1>::Constant(beta_1dim__, beta_2dim__,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      beta = in__.template read<
               Eigen::Matrix<local_scalar_t__,-1,-1>>(beta_1dim__,
               beta_2dim__);
      double alpha = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      alpha = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      Eigen::Matrix<double,-1,-1> log_mixing_weights =
        Eigen::Matrix<double,-1,-1>::Constant(N, K,
          std::numeric_limits<double>::quiet_NaN());
      for (int sym1__ = 1; sym1__ <= S; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
          out__.write(pi[(sym2__ - 1)][(sym1__ - 1)]);
        }
      }
      out__.write(beta);
      out__.write(alpha);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      {
        current_statement__ = 15;
        if (stan::math::logical_gt(K, 1)) {
          current_statement__ = 10;
          stan::math::validate_non_negative_index("eta", "N", N);
          current_statement__ = 11;
          stan::math::validate_non_negative_index("eta", "K - 1", (K - 1));
          Eigen::Matrix<double,-1,-1> eta =
            Eigen::Matrix<double,-1,-1>::Constant(N, (K - 1),
              std::numeric_limits<double>::quiet_NaN());
          current_statement__ = 12;
          stan::model::assign(eta,
            stan::math::multiply(X_design, stan::math::transpose(beta)),
            "assigning variable eta");
          current_statement__ = 13;
          stan::model::assign(log_mixing_weights,
            stan::math::append_col(eta, stan::math::rep_vector(0.0, N)),
            "assigning variable log_mixing_weights");
        } else {
          current_statement__ = 8;
          stan::model::assign(log_mixing_weights,
            stan::math::rep_matrix(0.0, N, 1),
            "assigning variable log_mixing_weights");
        }
      }
      if (emit_transformed_parameters__) {
        out__.write(log_mixing_weights);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      Eigen::Matrix<double,-1,-1> community_probs =
        Eigen::Matrix<double,-1,-1>::Constant(N, K,
          std::numeric_limits<double>::quiet_NaN());
      std::vector<int> z_hat =
        std::vector<int>(N, std::numeric_limits<int>::min());
      Eigen::Matrix<double,-1,1> log_lik =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 35;
      for (int i = 1; i <= N; ++i) {
        current_statement__ = 17;
        stan::math::validate_non_negative_index("log_weights", "K", K);
        Eigen::Matrix<double,-1,1> log_weights =
          Eigen::Matrix<double,-1,1>::Constant(K,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 18;
        stan::model::assign(log_weights,
          stan::math::log_softmax(
            stan::math::transpose(
              stan::model::rvalue(log_mixing_weights, "log_mixing_weights",
                stan::model::index_uni(i)))),
          "assigning variable log_weights");
        current_statement__ = 19;
        stan::math::validate_non_negative_index("lp", "K", K);
        Eigen::Matrix<double,-1,1> lp =
          Eigen::Matrix<double,-1,1>::Constant(K,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 28;
        for (int k = 1; k <= K; ++k) {
          current_statement__ = 21;
          stan::math::validate_non_negative_index("alpha_k", "S", S);
          Eigen::Matrix<double,-1,1> alpha_k =
            Eigen::Matrix<double,-1,1>::Constant(S,
              std::numeric_limits<double>::quiet_NaN());
          current_statement__ = 22;
          stan::model::assign(alpha_k,
            stan::math::multiply(alpha,
              stan::model::rvalue(pi, "pi", stan::model::index_uni(k))),
            "assigning variable alpha_k");
          double dm = std::numeric_limits<double>::quiet_NaN();
          current_statement__ = 23;
          dm = ((stan::model::rvalue(log_mc, "log_mc",
                   stan::model::index_uni(i))
            + stan::math::lgamma(alpha)) -
            stan::math::lgamma(
              (stan::model::rvalue(Ni, "Ni", stan::model::index_uni(i)) +
              alpha)));
          current_statement__ = 25;
          for (int s = 1; s <= S; ++s) {
            current_statement__ = 24;
            dm = (dm +
              (stan::math::lgamma(
                 (stan::model::rvalue(X, "X", stan::model::index_uni(i),
                    stan::model::index_uni(s)) +
                 stan::model::rvalue(alpha_k, "alpha_k",
                   stan::model::index_uni(s))))
              -
              stan::math::lgamma(
                stan::model::rvalue(alpha_k, "alpha_k",
                  stan::model::index_uni(s)))));
          }
          current_statement__ = 26;
          stan::model::assign(lp,
            (stan::model::rvalue(log_weights, "log_weights",
               stan::model::index_uni(k)) + dm), "assigning variable lp",
            stan::model::index_uni(k));
        }
        current_statement__ = 29;
        stan::model::assign(log_lik, stan::math::log_sum_exp(lp),
          "assigning variable log_lik", stan::model::index_uni(i));
        current_statement__ = 30;
        stan::math::validate_non_negative_index("post", "K", K);
        Eigen::Matrix<double,-1,1> post =
          Eigen::Matrix<double,-1,1>::Constant(K,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 31;
        stan::model::assign(post, stan::math::softmax(lp),
          "assigning variable post");
        current_statement__ = 32;
        stan::model::assign(community_probs, stan::math::transpose(post),
          "assigning variable community_probs", stan::model::index_uni(i));
        current_statement__ = 33;
        stan::model::assign(z_hat,
          stan::math::categorical_rng(post, base_rng__),
          "assigning variable z_hat", stan::model::index_uni(i));
      }
      current_statement__ = 6;
      stan::math::check_greater_or_equal(function__, "z_hat", z_hat, 1);
      current_statement__ = 6;
      stan::math::check_less_or_equal(function__, "z_hat", z_hat, K);
      out__.write(community_probs);
      out__.write(z_hat);
      out__.write(log_lik);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> pi =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(K,
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__));
      current_statement__ = 1;
      for (int sym1__ = 1; sym1__ <= S; ++sym1__) {
        current_statement__ = 1;
        for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
          current_statement__ = 1;
          stan::model::assign(pi, in__.read<local_scalar_t__>(),
            "assigning variable pi", stan::model::index_uni(sym2__),
            stan::model::index_uni(sym1__));
        }
      }
      out__.write_free_simplex(pi);
      Eigen::Matrix<local_scalar_t__,-1,-1> beta =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(beta_1dim__,
          beta_2dim__, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(beta,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(beta_1dim__,
          beta_2dim__), "assigning variable beta");
      out__.write(beta);
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 3;
      alpha = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, alpha);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "pi", "double",
        std::vector<size_t>{static_cast<size_t>(K), static_cast<size_t>(S)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "beta", "double",
        std::vector<size_t>{static_cast<size_t>(beta_1dim__),
          static_cast<size_t>(beta_2dim__)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "alpha", "double",
        std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> pi =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(K,
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__));
      {
        std::vector<local_scalar_t__> pi_flat__;
        current_statement__ = 1;
        pi_flat__ = context__.vals_r("pi");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= S; ++sym1__) {
          current_statement__ = 1;
          for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
            current_statement__ = 1;
            stan::model::assign(pi, pi_flat__[(pos__ - 1)],
              "assigning variable pi", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 1;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write_free_simplex(pi);
      Eigen::Matrix<local_scalar_t__,-1,-1> beta =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(beta_1dim__,
          beta_2dim__, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> beta_flat__;
        current_statement__ = 2;
        beta_flat__ = context__.vals_r("beta");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= beta_2dim__; ++sym1__) {
          current_statement__ = 2;
          for (int sym2__ = 1; sym2__ <= beta_1dim__; ++sym2__) {
            current_statement__ = 2;
            stan::model::assign(beta, beta_flat__[(pos__ - 1)],
              "assigning variable beta", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 2;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write(beta);
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 3;
      alpha = context__.vals_r("alpha")[(1 - 1)];
      out__.write_free_lb(0, alpha);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"pi", "beta", "alpha"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"log_mixing_weights"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"community_probs", "z_hat", "log_lik"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(K),
                                                 static_cast<size_t>(S)},
                std::vector<size_t>{static_cast<size_t>(beta_1dim__),
                  static_cast<size_t>(beta_2dim__)}, std::vector<size_t>{}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(N),
               static_cast<size_t>(K)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(N),
               static_cast<size_t>(K)},
             std::vector<size_t>{static_cast<size_t>(N)},
             std::vector<size_t>{static_cast<size_t>(N)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= S; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
        param_names__.emplace_back(std::string() + "pi" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= beta_2dim__; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= beta_1dim__; ++sym2__) {
        param_names__.emplace_back(std::string() + "beta" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    param_names__.emplace_back(std::string() + "alpha");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          param_names__.emplace_back(std::string() + "log_mixing_weights" +
            '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          param_names__.emplace_back(std::string() + "community_probs" + '.'
            + std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "z_hat" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= (S - 1); ++sym1__) {
      for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
        param_names__.emplace_back(std::string() + "pi" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= beta_2dim__; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= beta_1dim__; ++sym2__) {
        param_names__.emplace_back(std::string() + "beta" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    param_names__.emplace_back(std::string() + "alpha");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          param_names__.emplace_back(std::string() + "log_mixing_weights" +
            '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          param_names__.emplace_back(std::string() + "community_probs" + '.'
            + std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "z_hat" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"pi\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(K) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(S) + "}},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(beta_1dim__) + ",\"cols\":" + std::to_string(beta_2dim__) + "},\"block\":\"parameters\"},{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"log_mixing_weights\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N) + ",\"cols\":" + std::to_string(K) + "},\"block\":\"transformed_parameters\"},{\"name\":\"community_probs\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N) + ",\"cols\":" + std::to_string(K) + "},\"block\":\"generated_quantities\"},{\"name\":\"z_hat\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"int\"}},\"block\":\"generated_quantities\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"pi\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(K) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string((S -1)) + "}},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(beta_1dim__) + ",\"cols\":" + std::to_string(beta_2dim__) + "},\"block\":\"parameters\"},{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"log_mixing_weights\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N) + ",\"cols\":" + std::to_string(K) + "},\"block\":\"transformed_parameters\"},{\"name\":\"community_probs\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N) + ",\"cols\":" + std::to_string(K) + "},\"block\":\"generated_quantities\"},{\"name\":\"z_hat\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"int\"}},\"block\":\"generated_quantities\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((K * S) + (beta_1dim__ * beta_2dim__)) + 1);
    const size_t num_transformed = emit_transformed_parameters * ((N * K));
    const size_t num_gen_quantities = emit_generated_quantities * ((((N * K)
      + N) + N));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((K * S) + (beta_1dim__ * beta_2dim__)) + 1);
    const size_t num_transformed = emit_transformed_parameters * ((N * K));
    const size_t num_gen_quantities = emit_generated_quantities * ((((N * K)
      + N) + N));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_dmm_namespace::model_dmm;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_dmm_namespace::profiles__;
}
#endif
#endif
