#' Example eDNA metabarcoding dataset
#'
#' @description
#' A small simulated eDNA survey with known ground truth: 20 sites, 33 taxa,
#' four communities separated by depth and distance from shore. Use it to learn
#' the package, follow the vignettes (`vignette("tutorial")`), and verify your
#' installation.
#'
#' Load it via [get_example_data()].
#'
#' @format A named list with three elements:
#' \describe{
#'   \item{`counts`}{Integer matrix, 20 sites x 33 taxa. Rows are sites
#'     (`STN_001`-`STN_020`), columns are taxa (`Sp_1`, `Sp_2`, ...).}
#'   \item{`covariates`}{Data frame, 20 rows x 2 numeric columns: `Depth` (m)
#'     and `Distance_shore`. Numeric only, so it can be passed directly to
#'     [eDNA_dmm()].}
#'   \item{`metadata`}{Data frame, 20 rows: `sample_id`, `TrueCommunity`,
#'     `Depth`, `Distance_shore`. The labelling columns, for the plotting
#'     functions' `metadata` argument.}
#' }
#'
#' @section Community structure:
#' Four communities separated by two covariates:
#' \itemize{
#'   \item **Community 1**: deep (80 m) + offshore (200 units)
#'   \item **Community 2**: surface (10 m) + offshore (200 units)
#'   \item **Community 3**: deep (80 m) + inshore (20 units)
#'   \item **Community 4**: surface (10 m) + inshore (20 units)
#' }
#' Spillover = 0.15 (15% of frequency leaks between communities).
#' Overdispersion alpha = ~3.
#'
#' @source Generated by [simulate_eDNA_survey()] with `seed = 2026`.
#'   See `data-raw/generate_example_data.R` for the exact call. Only the fields
#'   a user needs are shipped; the simulation's internal tables are not.
#'
#' @examples
#' d <- get_example_data()
#' dim(d$counts)          # 20 x 33
#' head(d$covariates)
#'
#' @name example_edna
#' @docType data
#' @keywords datasets
NULL


#' Example eDNA dataset with replicates
#'
#' @description
#' The same survey as [example_edna], but with three replicates per site
#' instead of one pooled sample. Shipped so the expected shape of replicated
#' data is visible without having to simulate it first.
#'
#' Load it via [get_example_replicates()].
#'
#' @format A named list with four elements:
#' \describe{
#'   \item{`counts`}{Integer matrix, 60 replicates x 33 taxa. Row names are
#'     `STN_001_B1`, `STN_001_B2`, ... - three replicates per site.}
#'   \item{`replication`}{Character vector of length 60 giving the site each row
#'     belongs to. Pass as `replication` to [eDNA_dmm()].}
#'   \item{`covariates`}{Data frame, 20 rows x 2 numeric columns. Covariates are
#'     station-level: one row per site, not per replicate.}
#'   \item{`metadata`}{Data frame, 20 rows, station-level labelling columns.}
#' }
#'
#' @source Generated by [simulate_eDNA_survey()] with `seed = 2026` and
#'   `bio_reps = 3`. See `data-raw/generate_example_data.R`.
#'
#' @examples
#' r <- get_example_replicates()
#' dim(r$counts)           # 60 x 33
#' head(r$replication, 6)
#'
#' @name example_edna_reps
#' @docType data
#' @keywords datasets
NULL
