#' Example eDNA metabarcoding dataset
#'
#' @description
#' A small simulated eDNA survey with known ground truth: 20 sites, 33 taxa,
#' four communities separated by depth and distance from shore. Use it to learn
#' the package, follow the vignettes (`vignette("tutorial")`), and verify your
#' installation.
#'
#' Load it via [get_example_data()].
#'
#' @format A named list with three elements:
#' \describe{
#'   \item{`counts`}{Integer matrix, 20 sites x 33 taxa. Rows are sites
#'     (`STN_001`-`STN_020`), columns are taxa (`Sp_1`, `Sp_2`, ...).}
#'   \item{`covariates`}{Data frame, 20 rows x 2 numeric columns: `Depth` (m)
#'     and `Distance_shore`. Numeric only, so it can be passed directly to
#'     [eDNA_dmm()].}
#'   \item{`metadata`}{Data frame, 20 rows: `sample_id`, `TrueCommunity`,
#'     `Depth`, `Distance_shore`. The labelling columns, for the plotting
#'     functions' `metadata` argument.}
#' }
#'
#' @section Community structure:
#' Four communities separated by two covariates:
#' \itemize{
#'   \item **Community 1**: deep (80 m) + offshore (200 units)
#'   \item **Community 2**: surface (10 m) + offshore (200 units)
#'   \item **Community 3**: deep (80 m) + inshore (20 units)
#'   \item **Community 4**: surface (10 m) + inshore (20 units)
#' }
#' Spillover = 0.15 (15% of frequency leaks between communities).
#' Overdispersion alpha = ~3.
#'
#' @source Generated by [simulate_eDNA_survey()] with `seed = 2026`.
#'   See `data-raw/generate_example_data.R` for the exact call. Only the fields
#'   a user needs are shipped; the simulation's internal tables are not.
#'
#' @examples
#' d <- get_example_data()
#' dim(d$counts)          # 20 x 33
#' head(d$covariates)
#'
#' @name example_edna
#' @docType data
#' @keywords datasets
NULL
